openapi: 3.0.0

info:
    title: Cat Adoption API
    description: Just a simple API to help people adopt cats
    version: 0.1.0

paths:
    /cats:
        post:
            summary: add Cat
            description: this allows you to add a single cat.
            operationId: addCat

            requestBody:
                description: This is the cat object.
                content:
                    "application/json":
                        schema:
                            $ref: "#components/schemas/Cats"

            responses:
                "201":
                    description: The cat has been created.

        get:
            summary: get Cats
            description: this allows you to get all cats
            operationId: getCats

            responses:
                "200":
                    description: Succesful list of cats.
                    content:
                        application/json:
                            schema:
                                $ref: "#components/schemas/Cats"

    /cats/{id}:
        put:
            summary: update Cat
            description: this allows you to update a single cat.
            operationId: updateCat

            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                      $ref: "#components/schemas/Cats"

            requestBody:
                description: This is the cat object.
                content:
                    "application/json":
                        schema:
                            $ref: "#components/schemas/Cat"

            responses:
                "204":
                    description: The cat has been updated succesfully.

        get:
            summary: get Cat
            description: this allows you to get a single cat
            operationId: getCat

            parameters: 
                - name: id
                  in: path
                  required: true
                  schema:
                      $ref: "#components/schemas/Cat"

            responses:
                "200":
                    description: Succesful return of cat.
                    content:
                        application/json:
                            schema:
                                $ref: "#components/schemas/Cat"

components:
    schemas:
        Cats:
            type: array
            items:
                $ref: "#components/schemas/Cat"
        Cat:
            type: object
            required:
                - id
                - name
                - eyeColor
            properties:
                id:
                    type: integer
                name:
                    type: string
                description:
                    type: string
                owner:
                    type: string
                breed:
                    type: string
                age:
                    type: integer
                eyeColor:
                    type: array
                    items:
                        type: string
                weight:
                    type: integer
                fluffy:
                    type: boolean
                status:
                    type: string
                    enum:
                        - Adopted
                        - Available
                        - Unavailable
